module.exports.GET_ARTICLE ="GET_ARTICLE";
module.exports.GET_ARTICLE_START ="GET_ARTICLE_START";
module.exports.GET_ARTICLE_LIST ="GET_ARTICLE_LIST";
module.exports.GET_ARTICLE_LIST_START ="GET_ARTICLE_LIST_START";

module.exports.GET_USERS_START ="GET_USERS_START";
module.exports.GET_USERS ="GET_USERS";

module.exports.GET_IMAGES_START ="GET_IMAGES_START";
module.exports.GET_IMAGES ="GET_IMAGES";
module.exports.ACTIVATE_AJAX ="ACTIVATE_AJAX";
module.exports.CHANGE_DASHBOARD_TEXTAREA ="CHANGE_DASHBOARD_TEXTAREA";
module.exports.CHANGE_DASHBOARD_META="CHANGE_DASHBOARD_META";
module.exports.GET_REGISTRATION_COUNT="GET_REGISTRATION_COUNT";
module.exports.GET_REGISTRATION_COUNT_START="GET_REGISTRATION_COUNT_START";

