module.exports.GET_ARTICLE ="GET_ARTICLE";
module.exports.GET_ARTICLE_START ="GET_ARTICLE_START";
module.exports.GET_ARTICLE_LIST ="GET_ARTICLE_LIST";
module.exports.GET_ARTICLE_LIST_START ="GET_ARTICLE_LIST_START";